import os
import subprocess
import urllib.request
import urllib.parse
import zlib
import base64
import uuid
from docx import Document
from docx.shared import Inches
from pptx import Presentation
from pptx.util import Inches as PptxInches

def open_application(app_name: str):
    """
    Tries to open a common application on Windows by its name or executable.
    """
    print(f"Jarvis Tool: Opening {app_name}")
    
    # Map common tricky apps to their proper URIs/executables
    app_lower = app_name.lower()
    if 'spotify' in app_lower:
        app_name = 'spotify:'
    elif 'whatsapp' in app_lower:
        app_name = 'whatsapp:'
    elif 'word' in app_lower:
        app_name = 'winword'
    elif 'powerpoint' in app_lower:
        app_name = 'powerpnt'
        
    try:
        os.system(f"start {app_name}")
        return f"Successfully opened {app_name}."
    except Exception as e:
        return f"Failed to open {app_name}: {e}"

def create_word_document(topic: str, sections: list, template_path: str = None):
    """
    Creates a beautiful Word document.
    sections is a list of dicts: [{'heading': 'Intro', 'content': 'Hello', 'image_path': 'optional.png'}]
    """
    print(f"Jarvis Tool: Creating Word doc on {topic}")
    
    if template_path and os.path.exists(template_path):
        doc = Document(template_path)
    else:
        doc = Document()
        
    doc.add_heading(topic, 0) # Title style
    
    for sec in sections:
        if 'heading' in sec:
            doc.add_heading(sec['heading'], level=1)
        if 'content' in sec:
            doc.add_paragraph(sec['content'])
        if 'image_path' in sec and os.path.exists(sec['image_path']):
            try:
                doc.add_picture(sec['image_path'], width=Inches(5))
            except Exception:
                pass
                
    filename = f"{topic.replace(' ', '_')}.docx"
    doc.save(filename)
    
    try:
        os.startfile(filename)
    except Exception:
        pass
        
    return f"Created and opened Word document: {filename}"

def generate_flowchart_image(mermaid_code: str, filename: str = "flowchart.png"):
    """
    Renders Mermaid JS code into a beautiful PNG flowchart image.
    """
    print("Jarvis Tool: Generating flowchart")
    try:
        # Kroki requires base64-encoded compressed data
        compressed = zlib.compress(mermaid_code.encode('utf-8'), 9)
        encoded = base64.urlsafe_b64encode(compressed).decode('ascii')
        url = f"https://kroki.io/mermaid/png/{encoded}"
        urllib.request.urlretrieve(url, filename)
        return f"Successfully generated flowchart image at {filename}"
    except Exception as e:
        return f"Failed to generate flowchart: {e}"

def create_powerpoint(topic: str, slides: list):
    """
    Creates a simple PowerPoint presentation and opens it.
    slides should be a list of dicts: [{'title': 'Slide 1', 'points': ['Point 1', 'Point 2']}]
    """
    print(f"Jarvis Tool: Creating PPT on {topic}")
    prs = Presentation()
    
    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = topic
    subtitle.text = "Generated by Jarvis"
    
    # Bullet slides
    bullet_slide_layout = prs.slide_layouts[1]
    for slide_data in slides:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]
        
        title_shape.text = slide_data.get('title', 'Slide')
        tf = body_shape.text_frame
        
        points = slide_data.get('points', [])
        if points:
            tf.text = points[0]
            for point in points[1:]:
                p = tf.add_paragraph()
                p.text = point
                
        # Handle Dynamic AI Images
        image_prompt = slide_data.get('image_prompt')
        if image_prompt:
            try:
                temp_img = f"temp_slide_img_{uuid.uuid4().hex[:6]}.jpg"
                # Use Pollinations AI for stunning AI generated images
                url = f"https://image.pollinations.ai/prompt/{urllib.parse.quote_plus(image_prompt)}?width=800&height=600&nologo=true"
                urllib.request.urlretrieve(url, temp_img)
                # Insert picture on the right side of the slide
                slide.shapes.add_picture(temp_img, PptxInches(5), PptxInches(2.5), width=PptxInches(4.5))
            except Exception as e:
                print(f"Failed to fetch image: {e}")
        
    filename = f"{topic.replace(' ', '_')}.pptx"
    prs.save(filename)
    
    try:
        os.startfile(filename)
    except Exception:
        pass
        
    return f"Created and opened PowerPoint presentation: {filename}"



def run_terminal_command(command: str):
    """
    Executes an arbitrary terminal command (PowerShell/CMD) on the system.
    """
    print(f"Jarvis Tool: Running command -> {command}")
    try:
        # Run the command and capture output
        result = subprocess.run(
            ["powershell", "-Command", command],
            capture_output=True,
            text=True,
            shell=True
        )
        if result.returncode == 0:
            output = result.stdout.strip()
            return f"Command executed successfully. Output: {output[:500]}..." if output else "Command executed successfully with no output."
        else:
            return f"Command failed. Error: {result.stderr.strip()}"
    except Exception as e:
        return f"Failed to run command: {e}"

def write_code_file(filename: str, content: str):
    """
    Creates or overwrites a local file with the specified content.
    Useful for creating HTML, JS, Python, or text files directly.
    """
    print(f"Jarvis Tool: Writing file -> {filename}")
    try:
        os.makedirs(os.path.dirname(os.path.abspath(filename)), exist_ok=True)
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        # Attempt to open it in the default editor/browser
        os.startfile(filename)
        return f"Successfully created and opened {filename}."
    except Exception as e:
        return f"Failed to write file {filename}: {e}"
