import os
import subprocess
import urllib.request
import urllib.parse
import zlib
import base64
import uuid
from docx import Document
from docx.shared import Inches
from pptx import Presentation
from pptx.util import Inches as PptxInches

def open_application(app_name: str):
    """
    Tries to open a common application on Windows by its name or executable.
    """
    print(f"Jarvis Tool: Opening {app_name}")
    
    # Map common tricky apps to their proper URIs/executables
    app_lower = app_name.lower()
    if 'spotify' in app_lower:
        app_name = 'spotify:'
    elif 'whatsapp' in app_lower:
        app_name = 'whatsapp:'
    elif 'word' in app_lower:
        app_name = 'winword'
    elif 'powerpoint' in app_lower:
        app_name = 'powerpnt'
        
    try:
        os.system(f"start {app_name}")
        return f"Successfully opened {app_name}."
    except Exception as e:
        return f"Failed to open {app_name}: {e}"

def create_word_document(topic: str, sections: list, template_path: str = None):
    """
    Creates a beautiful Word document.
    sections is a list of dicts: [{'heading': 'Intro', 'content': 'Hello', 'image_path': 'optional.png'}]
    """
    print(f"Jarvis Tool: Creating Word doc on {topic}")
    
    if template_path and os.path.exists(template_path):
        doc = Document(template_path)
    else:
        doc = Document()
        
    doc.add_heading(topic, 0) # Title style
    
    for sec in sections:
        if 'heading' in sec:
            doc.add_heading(sec['heading'], level=1)
        if 'content' in sec:
            doc.add_paragraph(sec['content'])
        if 'image_path' in sec and os.path.exists(sec['image_path']):
            try:
                doc.add_picture(sec['image_path'], width=Inches(5))
            except Exception:
                pass
                
    filename = f"{topic.replace(' ', '_')}.docx"
    doc.save(filename)
    
    try:
        os.startfile(filename)
    except Exception:
        pass
        
    return f"Created and opened Word document: {filename}"

def generate_flowchart_image(mermaid_code: str, filename: str = "flowchart.png"):
    """
    Renders Mermaid JS code into a beautiful PNG flowchart image.
    """
    print("Jarvis Tool: Generating flowchart")
    try:
        # Kroki requires base64-encoded compressed data
        compressed = zlib.compress(mermaid_code.encode('utf-8'), 9)
        encoded = base64.urlsafe_b64encode(compressed).decode('ascii')
        url = f"https://kroki.io/mermaid/png/{encoded}"
        urllib.request.urlretrieve(url, filename)
        return f"Successfully generated flowchart image at {filename}"
    except Exception as e:
        return f"Failed to generate flowchart: {e}"

def create_powerpoint(topic: str, slides: list, template_path: str = None):
    """
    Creates a simple PowerPoint presentation and opens it.
    slides should be a list of dicts: [{'title': 'Slide 1', 'points': ['Point 1', 'Point 2']}]
    """
    print(f"Jarvis Tool: Creating PPT on {topic}")
    
    # Use the user's gorgeous template by default if they didn't specify one or if the path is invalid
    if not template_path or not os.path.exists(str(template_path)):
        default_template = r"C:\Users\CHINMAY MISHRA\Jarvis\Black Red and White Traditional Sunday Service Presentation (1).pptx"
        
        if "pitch" in topic.lower() or "deck" in topic.lower():
            import random
            pitch_templates = [
                r"C:\Users\CHINMAY MISHRA\Jarvis\TF34efa91b-fbff-4df4-8911-13715ceb5bc715e3ad05_wac-14eada426f78.pptx",
                r"C:\Users\CHINMAY MISHRA\Jarvis\TF8527a7e3-9e8b-40b7-811a-0420cf63f5c278d2b3b8_wac-16e6fda66a09.pptx"
            ]
            default_template = random.choice(pitch_templates)
            
        if os.path.exists(default_template):
            template_path = default_template
    
    if template_path and os.path.exists(template_path):
        prs = Presentation(template_path)
    else:
        prs = Presentation()
    
    # Try to safely use layouts (Title=0, Content=1)
    try:
        title_slide_layout = prs.slide_layouts[0]
        bullet_slide_layout = prs.slide_layouts[1]
    except Exception:
        title_slide_layout = prs.slide_layouts[0]
        bullet_slide_layout = prs.slide_layouts[0]
        
    # Title slide
    slide = prs.slides.add_slide(title_slide_layout)
    try:
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = topic
        subtitle.text = "Generated by Jarvis"
    except Exception:
        pass
    
    # Bullet slides
    bullet_slide_layout = prs.slide_layouts[1]
    for slide_data in slides:
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        try:
            title_shape = shapes.title
            title_shape.text = slide_data.get('title', 'Slide')
        except Exception:
            pass
            
        try:
            body_shape = shapes.placeholders[1]
            tf = body_shape.text_frame
            points = slide_data.get('points', [])
            if points:
                tf.text = points[0]
                for point in points[1:]:
                    p = tf.add_paragraph()
                    p.text = point
        except Exception:
            pass
                
        # Handle Dynamic AI Images
        image_prompt = slide_data.get('image_prompt')
        if image_prompt:
            temp_img = f"temp_slide_img_{uuid.uuid4().hex[:6]}.jpg"
            try:
                # Use Pollinations AI for stunning AI generated images.
                url = f"https://image.pollinations.ai/prompt/{urllib.parse.quote(image_prompt)}"
                req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
                with urllib.request.urlopen(req) as response, open(temp_img, 'wb') as out_file:
                    out_file.write(response.read())
            except Exception as e:
                print(f"Failed to fetch Pollinations image ({e}), falling back to Picsum photography...")
                # Fallback to random beautiful photography
                url = f"https://picsum.photos/seed/{uuid.uuid4().hex[:6]}/800/600"
                urllib.request.urlretrieve(url, temp_img)
            
            # Insert picture on the right side of the slide OR into a placeholder
            try:
                inserted = False
                for shape in slide.placeholders:
                    # 18 corresponds to PP_PLACEHOLDER.PICTURE
                    if hasattr(shape, "placeholder_format") and shape.placeholder_format.type == 18:
                        shape.insert_picture(temp_img)
                        inserted = True
                        break
                
                if not inserted:
                    slide.shapes.add_picture(temp_img, PptxInches(5), PptxInches(2.5), width=PptxInches(4.5))
            except Exception:
                pass
        
    filename = f"{topic.replace(' ', '_')}.pptx"
    prs.save(filename)
    
    try:
        os.startfile(filename)
    except Exception:
        pass
        
    return f"Created and opened PowerPoint presentation: {filename}"



def run_terminal_command(command: str):
    """
    Executes an arbitrary terminal command (PowerShell/CMD) on the system.
    """
    print(f"Jarvis Tool: Running command -> {command}")
    try:
        # Run the command and capture output
        result = subprocess.run(
            ["powershell", "-Command", command],
            capture_output=True,
            text=True,
            shell=True
        )
        if result.returncode == 0:
            output = result.stdout.strip()
            return f"Command executed successfully. Output: {output[:500]}..." if output else "Command executed successfully with no output."
        else:
            return f"Command failed. Error: {result.stderr.strip()}"
    except Exception as e:
        return f"Failed to run command: {e}"

def write_code_file(filename: str, content: str):
    """
    Creates or overwrites a local file with the specified content.
    Useful for creating HTML, JS, Python, or text files directly.
    """
    print(f"Jarvis Tool: Writing file -> {filename}")
    try:
        os.makedirs(os.path.dirname(os.path.abspath(filename)), exist_ok=True)
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        # Attempt to open it in the default editor/browser
        os.startfile(filename)
        return f"Successfully created and opened {filename}."
    except Exception as e:
        return f"Failed to write file {filename}: {e}"

def send_whatsapp_message(phone: str, text: str):
    """
    Opens the WhatsApp Desktop app with a pre-filled message to the specified phone number.
    """
    print(f"Jarvis Tool: Sending WhatsApp to {phone}")
    import urllib.parse
    try:
        # Strip any non-numeric characters except +
        clean_phone = "".join(c for c in phone if c.isdigit() or c == '+')
        encoded_text = urllib.parse.quote(text)
        url = f"whatsapp://send?phone={clean_phone}&text={encoded_text}"
        os.startfile(url)
        return f"Opened WhatsApp to send message to {phone}."
    except Exception as e:
        return f"Failed to open WhatsApp: {e}"

def draft_email(to: str, subject: str, body: str):
    """
    Opens Gmail in the default browser to draft an email.
    """
    print(f"Jarvis Tool: Drafting email to {to}")
    import urllib.parse
    import webbrowser
    try:
        encoded_subject = urllib.parse.quote(subject)
        encoded_body = urllib.parse.quote(body)
        url = f"https://mail.google.com/mail/?view=cm&fs=1&to={to}&su={encoded_subject}&body={encoded_body}"
        webbrowser.open(url)
        return f"Opened Gmail to draft email to {to}."
    except Exception as e:
        return f"Failed to open Gmail: {e}"

def build_antigravity_project(project_name: str, prompt: str):
    """
    Creates a new Antigravity project folder and runs the agy CLI to build the project.
    """
    import os
    import json
    import subprocess
    from audio.tts import speak
    from audio.stt import record_and_transcribe
    
    print(f"Jarvis Tool: Building Antigravity project {project_name}")
    
    base_dir = r"C:\Users\CHINMAY MISHRA\JarvisProjects"
    os.makedirs(base_dir, exist_ok=True)
    
    safe_name = "".join(c for c in project_name if c.isalnum() or c in (' ', '-', '_')).strip().replace(' ', '_')
    if not safe_name:
        safe_name = "Untitled_Project"
    project_dir = os.path.join(base_dir, safe_name)
    
    speak(f"I am about to build {safe_name}. Go ahead?")
    
    user_response = record_and_transcribe()
    print(f"User confirmation response: {user_response}")
    if not user_response or not any(word in user_response.lower() for word in ['yes', 'yeah', 'sure', 'do it', 'go ahead', 'okay', 'ok', 'yep']):
        return "Project creation cancelled by the user."
        
    speak("Starting the build process now. This might take a minute.")
    
    os.makedirs(project_dir, exist_ok=True)
    
    wrapped_prompt = f"""Project goal: {prompt}

Requirements:
- Scaffold a complete, runnable project in the current directory.
- Include a README.md explaining how to run it.
- Use sensible, modern defaults for the tech stack unless one was specified.
- Do not ask clarifying questions — make reasonable assumptions and note them in the README.
"""
    
    try:
        result = subprocess.run(
            ["agy", "-p", wrapped_prompt, "--dangerously-skip-permissions", "--output-format", "json"],
            cwd=project_dir,
            capture_output=True,
            text=True,
            shell=True
        )
        
        try:
            output_data = json.loads(result.stdout)
            return f"Successfully built the Antigravity project '{safe_name}' at {project_dir}."
        except json.JSONDecodeError:
            return f"Project build finished at {project_dir}. Output: {result.stdout[:300]}..."
            
    except Exception as e:
        return f"Failed to run the Antigravity CLI: {e}"

def analyze_screen(query: str):
    """
    Takes a screenshot of the main screen and uses Ollama's local vision model
    to answer the user's query about what is visible.
    """
    import os
    import pyautogui
    import tempfile
    import base64
    import urllib.request
    import json
    
    print(f"Jarvis Tool: Analyzing screen with Ollama for query: '{query}'")
    
    try:
        # Take screenshot
        fd, temp_path = tempfile.mkstemp(suffix=".png")
        os.close(fd)
        
        screenshot = pyautogui.screenshot()
        screenshot.save(temp_path)
        
        # Read and encode image to base64
        with open(temp_path, "rb") as img_file:
            img_b64 = base64.b64encode(img_file.read()).decode("utf-8")
        
        # Call Ollama API
        url = "http://localhost:11434/api/generate"
        data = {
            "model": "llava",
            "prompt": query,
            "images": [img_b64],
            "stream": False
        }
        
        req = urllib.request.Request(url, data=json.dumps(data).encode("utf-8"), headers={"Content-Type": "application/json"})
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode("utf-8"))
            answer = result.get("response", "No response from Ollama.")
            
        os.remove(temp_path)
        return answer
        
    except urllib.error.URLError:
        return "Failed to connect to Ollama. Make sure Ollama is installed, running, and you have pulled the vision model (run 'ollama run llava')."
    except Exception as e:
        return f"Failed to analyze screen: {e}"
